language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-beez' ]; then cd .. && eval "mv $currentfolder generator-beez" && cd generator-beez; fi

